services:
  passin-db:
    container_name: passin-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - passin-db:/var/lib/postgresql/data

volumes:
  passin-db: