// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: attendee.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countAttendeesByEvent = `-- name: CountAttendeesByEvent :one
SELECT COUNT(*) FROM attendees WHERE event_id = $1
`

func (q *Queries) CountAttendeesByEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttendeesByEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAttendeeByEmail = `-- name: GetAttendeeByEmail :one
SELECT id, name, email, created_at, updated_at, event_id FROM attendees WHERE email = $1 AND event_id = $2
`

type GetAttendeeByEmailParams struct {
	Email   string
	EventID uuid.UUID
}

func (q *Queries) GetAttendeeByEmail(ctx context.Context, arg GetAttendeeByEmailParams) (Attendee, error) {
	row := q.db.QueryRowContext(ctx, getAttendeeByEmail, arg.Email, arg.EventID)
	var i Attendee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EventID,
	)
	return i, err
}
