// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: event.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events(title, details, slug, maximum_attendees) VALUES($1, $2, $3, $4)
`

type CreateEventParams struct {
	Title            sql.NullString
	Details          sql.NullString
	Slug             sql.NullString
	MaximumAttendees sql.NullInt32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.Title,
		arg.Details,
		arg.Slug,
		arg.MaximumAttendees,
	)
	return err
}
