// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID               uuid.UUID
	Title            sql.NullString
	Details          sql.NullString
	Slug             sql.NullString
	MaximumAttendees sql.NullInt32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
