// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID               uuid.UUID
	Title            string
	Details          string
	Slug             string
	MaximumAttendees int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
